### PR TITLE
Support rln-same in rln-circuits-v2

### PR DESCRIPTION
**Pull request by mhchia**
## What's done?
It's part of https://github.com/Rate-Limiting-Nullifier/rlnjs/issues/17: Support [rln-same](https://github.com/Rate-Limiting-Nullifier/rln-circuits-v2/blob/main/circuits/rln-same.circom) from the rln-circuits-v2. This branch is **incompatible** with v1, and we still need to confirm whether it should be a standalone branch or it should be merged to `main` with a new version. Before that the PR is marked a draft to avoid being merged.

## How it's done?
- `messageId` is added as a private input and `messageLimit` as a public input
- `messageLimit` is checked when `verifyProof`
- README is updated

### Note
- waku.ts is deleted since this version is not compatible with js-rln
- This PR depends on #41 . Code diff: https://github.com/mhchia/rlnjs/compare/feat/latest-v1-circuit...feat/v2-circuit

### CODE REVIEW

**Comment by mhchia** [comment]
This PR is made a draft to avoid being accidentally merged. We still need to determine whether V2 should be supported simultaneously with V1 or it should just replace V1.

**Review by AtHeartEngineer — APPROVED** [review]

**Comment by AtHeartEngineer** [comment]
I have not tested this yet, but it looks good, I wasn't sure if your last PR depends on this one.

**Comment by mhchia** [comment]
Thanks for the review. Ah this PR depends on #41, i.e., this PR includes the changes in #41.

**Comment by mhchia** [comment]
Closed since it's included in #61

**Pull request closed without merging**
